#!/bin/bash

apt --yes dist-upgrade
apt build-dep --yes python3 python3-dev linux-headers-$(uname -r) build-essential mercurial tldr
apt install --yes python3 python3-dev linux-headers-$(uname -r) build-essential mercurial openssh-server openssh-client tldr
systemctl enable mariadb
systemctl enable ssh
